--- 
- name: CatPro Scanning
  hosts: all
  become: true
  gather_facts: true
  vars:
    timestamp: "{{ ansible_date_time.iso8601 }}"
    benchmark: VK_CIS-CAT-Assesor_with_license/Assessor/benchmarks/CIS_Red_Hat_Enterprise_Linux_9_Benchmark_v1.0.0-xccdf.xml
    profile: Level 1

  tasks:
    - name: Unzip catpro zip file
      ansible.builtin.unarchive:
        src: /root/VK_CIS-CAT-Assesor_with_license.zip
        dest: /root/ansible/
        remote_src: true
    
    - name: Assign permission to the script
      ansible.builtin.file:
        path: /root/ansible/VK_CIS-CAT-Assesor_with_license/Assessor
        mode: '0755'
        recurse: true

    - name: Run the CIS Benchmark script
      ansible.builtin.shell: 
        sh /root/ansible/VK_CIS-CAT-Assesor_with_license/Assessor/Assessor-CLI.sh 
        -b /root/ansible/{{ benchmark }}
        -p "Level 1"
        -rd /root/ansible/
        -rp report 
        -nts
        -html

    - name: copy the file from remote to localhost
      ansible.builtin.fetch:
        src: /root/ansible/report.html
        dest: /tmp/report/report_{{ timestamp }}.html
        group: awx
        mode: 0775
        flat: yes

      