---
- name: RHEL patching
  hosts: all 
  become: true
  gather_facts: true
  tasks:

    - name: 'Precheck | Get the precheck facts' 
      ansible.builtin.setup:
      register: precheck_facts_result

