---
# tasks file for report-html

# - name: Collect host facts
#   ansible.builtin.set_fact:
#     all_hosts_facts: "{{ ansible_play_hosts | map('extract', hostvars, 'ansible_facts') | list }}"
    
# for more than 1
# - name: Collect stats from all hosts
#   ansible.builtin.set_stats:
#     data:
#       all_hosts_facts: "{{ all_hosts_facts | default({}) | combine({item: hostvars[item].ansible_local.stats}) }}"
#     loop: "{{ groups['all'] }}"

  
# - name: Ensure default values for custom facts
#   ansible.builtin.set_fact:
#     all_hostname: "{{ all_hostname | default([]) }}"
#     all_hostname1: "{{ all_hostname1 | default([]) }}"
#     all_resolv: "{{ all_resolv | default([]) }}"
#     all_resolv1: "{{ all_resolv1 | default([]) }}"
#     all_mountpoint: "{{ all_mountpoint | default([]) }}"
#     all_mountpoint1: "{{ all_mountpoint1 | default([]) }}"

- name: Collect all facts into all_hosts_facts
  ansible.builtin.set_fact:
    all_hosts_facts: "{{ all_hosts_facts | default([]) + [{
      'hostname': inventory_hostname,
      'pre_distribution': pre_distribution,
      'post_distribution': post_distribution,
      'pre_kernel': pre_kernel,
      'post_kernel': post_kernel,
      'pre_memory': pre_memory,
      'post_memory': post_memory,
      'all_hostname': inventory_hostname ~ '_hosts_file_std',
      'all_hostname1': inventory_hostname ~ '_hosts_file_std1',
      'all_resolv': inventory_hostname ~ '_resolv_conf_std',
      'all_resolv1': inventory_hostname ~ '_resolv_conf_std1',
      'all_mountpoint': inventory_hostname ~ '_mount_point_std',
      'all_mountpoint1': inventory_hostname ~ '_mount_point_std1',
      'default_ipv4': ansible_facts.default_ipv4,
      'uptime_seconds': ansible_facts.uptime_seconds,
      'service_info_running': service_info_running,
      'pre_packages_ug': pre_packages_ug,
      'post_packages_ug': pre_packages_ug,
      'service_info2_running': service_info2_running
    }] }}"


- name: Display all hosts facts
  ansible.builtin.debug:
    var: all_hosts_facts

- name: Render details to template3
  ansible.builtin.template:
    src: details_template3.j2
    dest: /tmp/report/lvm_details.html
    var: all_hosts_facts
