---
# tasks file for report-html

- name: Collect host facts
  ansible.builtin.set_fact:
    all_hosts_facts: "{{ ansible_play_hosts | map('extract', hostvars, 'ansible_facts') | list }}"
    
- name: debug something
  ansible.builtin.debug:
    var: ansible_facts['all_hosts_facts']['mounts']

# - name: Ensure default values for custom facts
#   ansible.builtin.set_fact:
#     all_hostname: "{{ all_hostname | default([]) }}"
#     all_hostname1: "{{ all_hostname1 | default([]) }}"
#     all_resolv: "{{ all_resolv | default([]) }}"
#     all_resolv1: "{{ all_resolv1 | default([]) }}"
#     all_mountpoint: "{{ all_mountpoint | default([]) }}"
#     all_mountpoint1: "{{ all_mountpoint1 | default([]) }}"

- name: Render details to template
  ansible.builtin.template:
    src: details_template.j2
    dest: /tmp/report/lvm_details.html
  vars:
    all_hosts_facts: "{{ hostvars | map(attribute='ansible_facts') | list }}"

