---
- name: Snapshot for inventory 
  hosts: master-kvm
  become: yes
  gather_facts: true
  vars:
    ansible_user: '{{ mgd_username }}'
    ansible_become_password: '{{ mgd_password }}'
    ansible_password: '{{ mgd_password }}'
  roles:
    - snapshot-inventory
    