---
#for PV 
- name: Retrieve PV details
  ansible.builtin.command: pvdisplay
  register: pv_details

- name: Display PV details
  ansible.builtin.debug:
    var: pv_details.stdout

#for VG
- name: Retrieve VG details
  ansible.builtin.command: vgdisplay
  register: vg_details

- name: Display VG details
  ansible.builtin.debug:
    var: vg_details.stdout

#for LV
- name: Retrieve LV details
  ansible.builtin.command: lvdisplay
  register: lv_details

- name: Display LV details
  ansible.builtin.debug:
    var: lv_details.stdout

