---
#for PV 
- name: Retrieve PV details
  ansible.builtin.command: pvdisplay
  register: pv_details

#for VG
- name: Retrieve VG details
  ansible.builtin.command: vgdisplay
  register: vg_details

#for LV
- name: Retrieve LV details
  ansible.builtin.command: lvdisplay
  register: lv_details


- name: Render details to template
  ansible.builtin.template:
    src: details_template.j2
    dest: /tmp/lvm_details.txt
  vars:
    pv_details: "{{ pv_details }}"
    vg_details: "{{ vg_details }}"
    lv_details: "{{ lv_details }}"

