---
#for PV 
- name: Retrieve PV details
  ansible.builtin.command: pvdisplay
  register: pv_details

#for VG
- name: Retrieve VG details
  ansible.builtin.command: vgdisplay
  register: vg_details

#for LV
- name: Retrieve LV details
  ansible.builtin.command: lvdisplay
  register: lv_details



