---
- name: 'Precheck |  BLOCK : Gather all facts'
  block:
  # THIS PART ONWARDS IS FOR GATHER PRECHECK STATS AND SET INVENTORY_HOSTNAME 
    - name: OS-PRE | Get the precheck facts
      ansible.builtin.setup:
      register: precheck_facts_result

    - name: OS-PRE | Set stats with dynamic key
      ansible.builtin.set_stats:
        data:
          "{{ inventory_hostname | replace('.', '_') }}_precheck_facts_result": "{{ precheck_facts_result }}"

# THIS PART ONWARDS IS FOR DISTRIBUTION STATS & SET INVENTORY_HOSTNAME
    - name: OS-PRE | Set distribution stats
      ansible.builtin.set_stats:
        data:
          "{{ inventory_hostname | replace('.', '_') }}_pre_distribution":  "{{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} "

# THIS PART ONWARDS IS FOR OS VERSION STATS & SET INVENTORY_HOSTNAME
    - name: OS-PRE | Set kernel Version stats
      ansible.builtin.set_stats:
        data:
          "{{ inventory_hostname | replace('.', '_') }}_pre_kernel": "{{ ansible_facts['kernel'] }}"

# THIS PART ONWARDS IS FOR MEMORY STATS & SET INVENTORY_HOSNTMAE
    - name: OS-PRE | Set memory stats
      ansible.builtin.set_stats:
        data:
          "{{ inventory_hostname | replace('.', '_') }}_pre_memory": "{{ ansible_facts['memtotal_mb'] }}"

# THIS PART ONWARDS IS FOR /ETC/HOSTS & SET INVENTORY_HOSTNAME
    - name: OS-PRE | Read /etc/hosts file
      ansible.builtin.command: cat /etc/hosts 
      register: hosts_file

    - name: OS-PRE | debug hosts_file into set_stats
      ansible.builtin.set_stats:
        data:
          "{{ inventory_hostname | replace('.', '_') }}_pre_host_file": "{{ hosts_file.stdout_lines | default([]) }}"


# THIS PART ONWARDS IS FOR /ETC/RESOLV & SET INVENTORY_HOSTNAME
    - name:  OS-PRE| Read /etc/resolv.conf
      ansible.builtin.command: cat /etc/resolv.conf
      register: resolv_conf

    - name: OS-PRE| debug resolve_conf into set_stats
      ansible.builtin.set_stats:
        data:
          "{{ inventory_hostname | replace('.', '_') }}_pre_resolv_conf": "{{ resolv_conf.stdout_lines | default([]) }}"



# # THIS PART ONWARDS IS FOR MOUNT POINT & SET INVENTORY_HOSTNAME

    - name: OS-PRE | Check mount point
      ansible.builtin.debug:
        msg: "{{ ansible_facts['mounts'] }}"
      register: mount_point

    - name: OS-PRE | Debug mount_point into set_stats
      ansible.builtin.set_stats:
        data:
          "{{ inventory_hostname | replace('.', '_') }}_pre_mount_point": "{{ mount_point['msg'] | default([]) }}"

  rescue:
    - name: 'GATHER_FACTS |  Set failure message'
      ansible.builtin.set_fact:
        pre_check_status: false
        pre_check_fail: true
        pre_check_fail_stage: 'GATHER_FACTS'
        pre_check_fail_msg: "{{ ansible_failed_result }}"  

