---
- name: 'OS-PRE | Set default facts'
  ansible.builtin.set_fact:
    pre_check_status: true
    pre_check_fail: false
    pre_check_fail_stage: ''
    pre_check_fail_msg: '' 

- name: 'OS-PRE | Gather all facts'
  ansible.builtin.include_tasks:
    file: 'gather_all_facts_masterv2.yml'
  when: not pre_check_fail

# - name: 'OS-PRE | Check for patching list '
#   ansible.builtin.include_tasks:
#     file: 'pre_patch_master.yml'
#   when: not pre_check_fail

# - name: 'OS-PRE | Check for running list '
#   ansible.builtin.include_tasks:
#     file: 'pre_file_master.yml'
#   when: not pre_check_fail
