---
# tasks file for os-pre
- name: Ensure the OS checks directory exists
  ansible.builtin.file:
    path: /var/backup/OS_checks/
    state: directory
    mode: '0755'

- name: Get manufacturer information of the virtual machine
  ansible.builtin.debug:
    msg: "The manufacturer of the VM is {{ ansible_facts['ansible_system_vendor'] }}"