---
# - name: check if {{ pre }} exists
#   ansible.builtin.stat:
#     path: "{{ pre }}" 
#   register: pre_exists

# - name: rename file
#   ansible.builtin.command: mv "{{ pre }}" "{{ pre }}.{{ansible_facts['date_time']['iso8601']}}"
#   when: pre_exists.stat.exists 

- name: 'GATHER_FACTS | Get service facts'
  ansible.builtin.service_facts:
  register: precheck_service_result

- name: Create a list of running services
  ansible.builtin.set_fact:
    service_info_running: "{{ precheck_service_result.ansible_facts.services | dict2items | selectattr('value.state', 'equalto', 'running') | map(attribute='key') | list }}"

# - name: Create a list of running services
#   ansible.builtin.set_stats:
#     data:
#       service_info_running: "{{ precheck_service_result.ansible_facts.services | selectattr('state', 'equalto', 'running') | map(attribute='key') | list }}"

