---
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  check_mode: true
  register: packages_ug

- name: debug packages_ug
  ansible.builtin.debug:
    msg: "{{ packages_ug['results'] }}"
  register: packages_ug1

- name: set_fact for packages_ug
  ansible.builtin.set_fact:
      pre_packages_ug : "{{ packages_ug1 }}"
      
    # - name: Separate installed packages
    #   ansible.builtin.set_fact:
    #     installed_packages: "{{ packages | select('search', '^Installed:') | list }}"


# "{{ ansible_checks.updates | dict2items | map(attribute='value.kb') | list }}" 