---
- name: OS-PRE | Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest 
  check_mode: true
  register: packages_ug

- name: OS-PRE | debug packages_ug
  ansible.builtin.debug:
    msg: "{{ packages_ug['results'] }}"
  register: packages_ug1

- name: OS-PRE | set_fact for packages_ug
  ansible.builtin.set_stats:
    data:
      pre_packages_ug : "{{ packages_ug1['msg'] | dict2items | list }}"