---
# THIS FILE IS FOR GETTING PRE PATCH LIST ONLY AND STATS - NOT PATCHIN
- name: OS-PRE | Upgrade all packages
  ansible.builtin.yum:
    name: "*"
    state: latest 
  check_mode: true
  register: pre_packages_ug

- name: OS-PRE | debug packages_ug
  ansible.builtin.debug:
    msg: "{{ pre_packages_ug['results'] }}"
  register: pre_upgrade

- name: OS-PRE | set_stats for packages_ug
  ansible.builtin.set_stats:
    data:
      "{{ inventory_hostname | replace('.', '_') }}_pre_packages_ug": "{{ pre_upgrade['msg'] }}"



            