---
# tasks file for os-patch

- name: 'Precheck | Set default facts'
  ansible.builtin.set_fact:
    pre_check_status: true
    pre_check_fail: false
    pre_check_fail_stage: ''
    pre_check_fail_msg: '' 
    
- name: 'Patch | Update'
  ansible.builtin.include_tasks:
    file: 'patch.yml'
  when: not pre_check_fail
