---
# THIS FILE IS FOR UPGRADE KEEP IN STATS AND INVENTORY HOSTNAME
- name: PATCH | Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  register: patch_ug

- name: PATCH | Ensure updates are registered
  ansible.builtin.set_stats:
    data:
      "{{ inventory_hostname}}_updates": "{{ patch_ug.results | map(attribute='updates') | select('defined') | list | first | default({}) }}"


- name: PATCH | Reboot machine
  ansible.builtin.reboot:
    pre_reboot_delay: 60

