---
- name: OS-POST | Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  check_mode: true
  register: post_packages_ug

- name: OS-POST | debug packages_ug
  ansible.builtin.debug:
    msg: "{{ post_packages_ug['results'] }}"
  register: post_packages_ug1

- name: OS-POST | set_fact for packages_ug
  ansible.builtin.set_fact:
    post_packages_ug : "{{ post_packages_ug['msg'] }}"

- name: OS-POST | set_fact for packages_ug
  ansible.builtin.set_stats:
    post_packages_ug : "{{ post_packages_ug }}"

- name: OS-POST | set_stats for packages_ug
  ansible.builtin.set_stats:
    data:
      post_packages_ug : "{{ post_packages_ug }}"