---
- name: 'GATHER_FACTS | Get service facts'
  ansible.builtin.service_facts:
    register: postcheck_servicefacts_result

- name: Create a list of running services
  ansible.builtin.set_fact:
    service_info2_running: "{{ postcheck_servicefacts_result.services | selectattr('state', 'equalto', 'started') | map(attribute='display_name') | list }}"
  