---
# THIS FILE IS FOR GETTING POST PATCH LIST ONLY AND STATS - NOT PATCHING
- name: OS-POST | Upgrade all packages
  ansible.builtin.yum:
    name: "*"
    state: latest
  check_mode: true
  register: post_packages_ug

- name: OS-POST | debug packages_ug
  ansible.builtin.debug:
    msg: "{{ post_packages_ug['results'] }}"
  register: post_upgrade

- name: OS-POST | set_stats for packages_ug
  ansible.builtin.set_stats:
    data:
      "{{ inventory_hostname | replace('.', '_') }}_post_packages_ug": "{{ post_upgrade['msg'] }}"
