- name: ' OS-POST |  BLOCK : Capture all patching results'
  block:
    - name: 'OS-POST | Capture the yum update history'
      ansible.builtin.shell: yum history info
      register: yum_update_history_result
