---
# tasks file for os-pre
- name: Ensure the OS checks directory exists
  ansible.builtin.file:
    path: /var/backup/OS_checks/
    state: directory
    mode: '0755'

- name: Get manufacturer information of the virtual machine
